import "./globals.css";
import type { Metadata } from "next";
import { Inter, Permanent_Marker } from "next/font/google";
import Link from "next/link";
import { cn } from "../lib/utils";

const inter = Inter({ subsets: ["latin"] });
const permenantMarker = Permanent_Marker({ weight: "400", subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Dong-Island",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navList = [
    { name: "Home", href: "/" },
    { name: "Room", href: "/room" },
  ];
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex justify-around my-4">
          {navList.map(({ name, href }) => (
            <Link
              className={cn(
                permenantMarker.className,
                "bg-amber-300  text-2xl shadow-xl flex rounded-full shadow-[0px_15px_15px_15px_#fcd34d]  justify-center align-middle"
              )}
              key={name}
              href={href}
            >
              <div className="border-b rounded-full py-4 px-12 bg-violet-800/70  hover:bg-gray-100 hover:text-gray-900 animate-[bounce_5s_infinite] ">
                {name}
              </div>
            </Link>
          ))}
        </nav>
        {children}
      </body>
    </html>
  );
}
